services:
  app:
    image: php:8.2-apache
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nome_db
      MYSQL_USER: utente
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: utente
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data: